using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace CoCApp.DataAccess.Sql.Migrations
{
    public partial class seedinspectorskills : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(table: "SkillDefinitions", 
                columns: new[] {"Id","Name", "Description", "MinimumLevel", "CreatedDate"}, 
                values: new object[,] 
                { 
                    {Guid.NewGuid(),"Accounting", "Grants understanding of accountancy procedures and reveals the financial functioning of a business or person. Inspecting the  books,  one  might  detect  cheated  employees,  siphoned-off  funds,  payment  of  bribes  or  blackmail,  and  whether  the  financial condition is better or worse than claimed. Looking through old accounts, one could see how money was gained or  lost  in  the  past  (grain,  slave-trading,  whiskey-running,  etc.) and to whom and for what payment was made.", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Acting", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Animal Handling", " e ability to command and train domesticated animals to perform simple tasks.   e skill is most commonly applied to dogs but may include birds, cats, monkeys, and so on (at the Keeper’s  discretion).  For  riding  animals,  such  as  horses  or  camels, the Ride skill is used for breaking-in and controlling such mounts.", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Anthropology", "Enables the user to identify and understand an individual’s way  of  life  through  observation.  If  the  skill-user  observes  another  culture  from  within  for  a  time,  or  works  from  accurate records concerning an extinct culture, then simple predictions can be made about that culture’s ways and morals, even though the evidence may be incomplete. Studying the culture  for  a  month  or  more,  the  anthropologist  begins  to  understand how the culture functions and, in combination with  Psychology,  may  predict  the  actions  and  beliefs  of  those being studied.", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Appraise", "Used to estimate the value of a particular item, including the quality,  material  used,  and  workmanship.  Where  relevant,  the  skill-user  could  pinpoint  the  age  of  the  item,  assess  its  historical relevance, and detect forgeries", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Archaeology", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Art and Craft", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Artillery", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Astronomy", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Axe", "", "15", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Biology", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Botany", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Bow", "", "15", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Brawl", "", "25", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Chainsaw", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Charm", "", "15", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Chemistry", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Climb", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Computer Use", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Credit Rating", "", "0", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Cryptography", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Cthulhu Mythos", "", "0", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Demolitions", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Disguise", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Diving", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Dodge", "", "-1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Drive Auto", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Electrical Repair", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Electronics", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Engineering", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Fast Talk", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Fighting", "", "-1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Fine Art", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Firearms", "", "-1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"First Aid", "", "30", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Flail", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Flamethrower", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Forensics", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Forgery", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Garrote", "", "15", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Geology", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Handgun", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Heavy Weapons", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"History", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Hypnosis", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Intimidate", "", "15", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Jump", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Language (Other)", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Language (Own)", "", "-1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Law", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Library Use", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Listen", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Locksmith", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Lore", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Machine Gun", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Mathematics", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Mechanical Repair", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Medicine", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Meteorology", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Natural World", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Navigate", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Occult", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Operate Heavy Machinery  ", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Persuade", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Pharmacy", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Photography  ", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Physics", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Pilot", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Psychoanalysis  ", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Psychology", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Read Lips", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Ride", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Rifle", "", "25", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Science", "", "1", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Shotgun", "", "25", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Sleight of Hand ", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Spear", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Spot Hidden", "", "25", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Stealth", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Submachine Gun  ", "", "15", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Survival", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Swim", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Sword", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Throw", "", "20", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Track", "", "10", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Whip", "", "5", DateTimeOffset.Now},
                    {Guid.NewGuid(),"Zoology", "", "1", DateTimeOffset.Now},
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("truncate table [dbo].[SkillDefinitions]");
        }
    }
}
